In [1]:
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
import pandas as pd

Using TensorFlow backend.


In [156]:
input_path = 'data/Elearning-Data-cut.xls'
train_data_count = 720

In [157]:
def read_input():
    input = pd.read_excel(input_path, 0)
    input = input.drop(['STUDENTN'], axis=1)
    input = input.fillna(0)
    output_gpa = pd.read_excel(input_path, 1)
    output_fail = pd.read_excel(input_path, 2)[['OUT_IN']]
    return input, output_gpa, output_fail

In [158]:

print("Hi")
input, output_gpa, output_fail = read_input()
input = input.to_numpy()
output_gpa = output_gpa.to_numpy()
output_fail = output_fail.to_numpy()
X_train = input[:train_data_count]
Y_train = output_gpa[:train_data_count]
Y_train2 = output_fail[:train_data_count]
X_test = input[train_data_count:]
Y_test = output_gpa[train_data_count:]
Y_test2 = output_fail[train_data_count:]

X_train = keras.utils.normalize(X_train)
X_test = keras.utils.normalize(X_test)
print(Y_test2)

Hi
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [167]:
model = Sequential()
# model.add(Input(27,(27,)))
model.add(Dense(500, activation='relu'))
model.add(Dropout(0.01))
model.add(Dense(300, activation='relu'))
model.add(Dropout(0.01))
model.add(Dense(200, activation='relu'))
model.add(Dropout(0.01))
model.add(Dense(100, activation='relu'))
model.add(Dropout(0.01))
model.add(Dense(50, activation='relu'))
model.add(Dropout(0.01))
model.add(Dense(1, activation='relu'))
sgd = keras.optimizers.sgd(lr=0.05, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(optimizer='sgd', loss='mape', metrics=['mae'])
model.fit(X_train, Y_train, batch_size=3, epochs=100)

Epoch 1/100
720/720 [==============================] - 1s 1ms/step - loss: 27.8488 - mae: 3.8071
Epoch 2/100
720/720 [==============================] - 1s 707us/step - loss: 18.2963 - mae: 2.4483
Epoch 3/100
720/720 [==============================] - 1s 695us/step - loss: 18.1455 - mae: 2.4661
Epoch 4/100
720/720 [==============================] - 1s 755us/step - loss: 18.2351 - mae: 2.4637
Epoch 5/100
720/720 [==============================] - 0s 630us/step - loss: 17.7074 - mae: 2.3793
Epoch 6/100
720/720 [==============================] - 1s 842us/step - loss: 17.8052 - mae: 2.4111
Epoch 7/100
720/720 [==============================] - 1s 795us/step - loss: 18.0911 - mae: 2.4286
Epoch 8/100
720/720 [==============================] - 0s 693us/step - loss: 17.8941 - mae: 2.4190
Epoch 9/100
720/720 [==============================] - 0s 651us/step - loss: 17.5857 - mae: 2.3509
Epoch 10/100
720/720 [==============================] - 0s 599us/step - loss: 17.2803 - mae: 2.2936
Epoch 11/10

720/720 [==============================] - 1s 897us/step - loss: 13.1845 - mae: 1.7107
Epoch 84/100
720/720 [==============================] - 1s 884us/step - loss: 13.8297 - mae: 1.8078
Epoch 85/100
720/720 [==============================] - 1s 1ms/step - loss: 13.4357 - mae: 1.7434
Epoch 86/100
720/720 [==============================] - 1s 752us/step - loss: 13.3315 - mae: 1.7342
Epoch 87/100
720/720 [==============================] - 1s 1ms/step - loss: 13.9582 - mae: 1.8217
Epoch 88/100
720/720 [==============================] - 1s 809us/step - loss: 13.4818 - mae: 1.7579
Epoch 89/100
720/720 [==============================] - 1s 1ms/step - loss: 13.3590 - mae: 1.7446
Epoch 90/100
720/720 [==============================] - 1s 828us/step - loss: 13.7149 - mae: 1.7600
Epoch 91/100
720/720 [==============================] - 1s 836us/step - loss: 14.0582 - mae: 1.8462
Epoch 92/100
720/720 [==============================] - 0s 587us/step - loss: 13.0579 - mae: 1.6852
Epoch 93/100
720/72

In [168]:
model.evaluate(X_test,Y_test)

20/20 [==============================] - 0s 4ms/step


[10.671063423156738, 1.6960649490356445]

In [169]:
model.predict(X_test)

array([[15.864969 ],
       [13.931728 ],
       [11.953044 ],
       [15.311611 ],
       [14.889722 ],
       [16.075474 ],
       [11.953044 ],
       [15.175665 ],
       [13.793318 ],
       [14.951307 ],
       [14.951307 ],
       [16.10532  ],
       [16.063969 ],
       [15.87022  ],
       [11.953044 ],
       [15.01955  ],
       [15.336937 ],
       [11.953044 ],
       [14.8879795],
       [14.479078 ]], dtype=float32)

In [170]:
model2 = Sequential()
# model.add(Input(27,(27,)))
model2.add(Dense(300, activation='relu'))
model2.add(Dense(300, activation='relu'))
model2.add(Dropout(0.01))
model2.add(Dense(200, activation='relu'))
model2.add(Dropout(0.01))
model2.add(Dense(100, activation='relu'))
model2.add(Dropout(0.01))
model2.add(Dense(50, activation='sigmoid'))
model2.add(Dropout(0.01))
model2.add(Dense(1, activation='softmax'))
sgd = keras.optimizers.sgd(lr=0.05, decay=1e-6, momentum=0.9, nesterov=True)
model2.compile(optimizer='Nadam', loss='binary_crossentropy', metrics=['accuracy'])
model2.fit(X_train, Y_train2, batch_size=5, epochs=100)
model2.evaluate(X_test, Y_test2)

Epoch 1/100
720/720 [==============================] - 1s 2ms/step - loss: 2.5981 - accuracy: 0.8306
Epoch 2/100
720/720 [==============================] - 1s 861us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 3/100
720/720 [==============================] - 1s 737us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 4/100
720/720 [==============================] - 0s 638us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 5/100
720/720 [==============================] - 0s 666us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 6/100
720/720 [==============================] - 0s 657us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 7/100
720/720 [==============================] - 0s 657us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 8/100
720/720 [==============================] - 0s 601us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 9/100
720/720 [==============================] - 0s 604us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 10/100
720/720 [==============================] - 0s 570us/step - los

720/720 [==============================] - 0s 530us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 80/100
720/720 [==============================] - 0s 611us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 81/100
720/720 [==============================] - 0s 635us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 82/100
720/720 [==============================] - 0s 575us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 83/100
720/720 [==============================] - 0s 558us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 84/100
720/720 [==============================] - 0s 642us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 85/100
720/720 [==============================] - 0s 643us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 86/100
720/720 [==============================] - 0s 544us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 87/100
720/720 [==============================] - 0s 594us/step - loss: 2.5981 - accuracy: 0.8306
Epoch 88/100
720/720 [==============================] - 0s 521us/step - loss:

[0.0, 1.0]

In [171]:
model2.evaluate(X_test,Y_test2)

20/20 [==============================] - 0s 70us/step


[0.0, 1.0]

In [172]:
model2.predict(X_test)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)